@startuml
actor Nutritionist
participant ":UI" as UI
participant ":LogicManager" as LogicManager
participant ":AddCommandParser" as AddCommandParser
participant ":AddCommand" as AddCommand
participant ":Model" as Model

Nutritionist -> UI : enter "add ..."
UI -> LogicManager : execute("add ...")
LogicManager -> AddCommandParser : parse("add ...")
AddCommandParser -> AddCommand : new AddCommand(toAdd)
LogicManager -> AddCommand : execute(model)
AddCommand -> Model : hasPerson(toAdd)
alt Person exists
    AddCommand -> LogicManager : throw CommandException
else Person is unique
    AddCommand -> Model : addPerson(toAdd)
end
AddCommand -> LogicManager : return CommandResult
LogicManager -> UI : show success message

hide footbox
@enduml
