@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

VersionedAddressBook *-right-> "1" UniquePersonList
VersionedAddressBook *-right-> "1" UniqueAllergyList
UniqueAllergyList -[hidden]down- UniquePersonList
UniqueAllergyList -[hidden]down- UniquePersonList

UniqueAllergyList -right-> "*" Allergy
UniquePersonList -right-> Person

Person -up-> "*" Allergy

Person *---> Name
Person *---> Phone
Person *---> Address
Person *---> Email
Person *---> Weight
Person *---> Height
Person *---> Gender
Person *---> Diet
Person *---> MeetingDate
Person *---> Priority
Person *---> "0..1"Remark

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Email -[hidden]right-> Weight
Weight -[hidden]right-> Height
Height -[hidden]right-> Gender
Gender -[hidden]right-> Diet
Diet -[hidden]right-> MeetingDate
MeetingDate -[hidden]right-> Priority
Priority -[hidden]right-> Remark
@enduml
