@startuml
actor Nutritionist
participant UI
participant LogicManager
participant ClearCommand
participant Model

Nutritionist -> UI : enter "clear"
UI -> LogicManager : execute("clear")
LogicManager -> ClearCommand : execute(model)
ClearCommand -> Model : setAddressBook(new AddressBook)
ClearCommand -> LogicManager : return CommandResult
LogicManager -> UI : update patient list

hide footbox
@enduml
