@startuml
!include style.puml
skinparam ArrowFontStyle plain

actor User USER_COLOR

participant ":UI" as UI UI_COLOR
participant ":Logic" as Logic LOGIC_COLOR
participant ":CommandHistory" as CommandHistory #Brown

User -[USER_COLOR]> UI : handleCommandEntered(commandText)
activate UI UI_COLOR

UI -[UI_COLOR]> Logic : execute(commandText)
activate Logic LOGIC_COLOR

Logic -[LOGIC_COLOR]> CommandHistory : addCommand(commandText)
activate CommandHistory #Brown
CommandHistory --[#Brown]> Logic
deactivate CommandHistory

Logic --[LOGIC_COLOR]> UI
deactivate Logic
deactivate UI

User -[USER_COLOR]> UI : handleKeyPressed(UP)
activate UI UI_COLOR
UI -[UI_COLOR]> CommandHistory : getPreviousCommand()
activate CommandHistory #Brown
CommandHistory --[#Brown]> UI : previousCommand
deactivate CommandHistory
deactivate UI

User -[USER_COLOR]> UI : handleKeyPressed(DOWN)
activate UI UI_COLOR
UI -[UI_COLOR]> CommandHistory : getNextCommand()
activate CommandHistory #Brown
CommandHistory --[#Brown]> UI : nextCommand
deactivate CommandHistory
deactivate UI

@enduml
