@startuml
class AddCommand {
  - Person toAdd
  + AddCommand(Person)
  + CommandResult execute(Model)
}

class AddCommandParser {
  + AddCommand parse(String args)
}

class Person

AddCommand --> Person
AddCommandParser --> AddCommand
@enduml
